version: '3.3'

services:  

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.howntnx.win`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.certresolver=cloudflare'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.howntnx.win'  # yamllint disable-line rule:line-length
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=Australia/Melbourne


  traefik:
    image: traefik:2.6
    container_name: traefik
    restart: unless-stopped
    volumes:
      - ./traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.howntnx.win`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.tls.certresolver=cloudflare'
      - 'traefik.http.routers.api.middlewares=authelia@docker'
    ports:
      - 80:80
      - 443:443
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--certificatesResolvers.cloudflare.acme.email=ariesbabu@gmail.com'
      - '--certificatesResolvers.cloudflare.acme.storage=acme.json'
      - '--certificatesResolvers.cloudflare.acme.httpChallenge.entryPoint=http'
      - '--log=true'
      - '--log.level=INFO'
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  how:
    image: ariesbabu/sphinx-how
    container_name: how
    restart: unless-stopped
    command: live
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.webapp1.rule=Host(`ocp.howntnx.win`)'
      - 'traefik.http.routers.webapp1.entrypoints=https'
      - 'traefik.http.routers.webapp1.tls=true'
      - 'traefik.http.routers.webapp1.tls.certresolver=cloudflare'
      - 'traefik.http.routers.webapp1.service=webappservice1'
      - 'traefik.http.services.webappservice1.loadbalancer.server.port=8000'
      - 'traefik.http.routers.webapp1.middlewares=authelia@docker'
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/ubuntu/za/source:/wd
    ports:
      - 8000:8000
  
  how1:
    image: ariesbabu/sphinx-how
    container_name: how1
    restart: unless-stopped
    command: live
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.webapp2.rule=Host(`nhtd1.howntnx.win`)'
      - 'traefik.http.routers.webapp2.entrypoints=https'
      - 'traefik.http.routers.webapp2.tls=true'
      - 'traefik.http.routers.webapp2.tls.certresolver=cloudflare'
      - 'traefik.http.routers.webapp2.service=webappservice2'
      - 'traefik.http.services.webappservice2.loadbalancer.server.port=8001'
      - 'traefik.http.routers.webapp2.middlewares=authelia@docker'
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/ubuntu/za/source/nhtd1:/wd
    ports:
      - 8001:8000
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.manage.rule=Host(`manage.howntnx.win`)'
      - 'traefik.http.routers.manage.entrypoints=https'
      - 'traefik.http.routers.manage.tls=true'
      - 'traefik.http.routers.manage.tls.certresolver=cloudflare'
      - 'traefik.http.routers.manage.service=manageservice'
      - 'traefik.http.services.manageservice.loadbalancer.server.port=9000'
      - 'traefik.http.routers.manage.middlewares=authelia@docker'
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000